package com.example.motivationcalendarapi.model.reward

import com.example.motivationcalendarapi.R

object RewardDefinitions {
    val all: List<RewardDefinition> = listOf(
        RewardDefinition("total_workouts", RewardType.TOTAL_WORKOUTS, RewardStringRefs(R.string.reward_total_workouts_title, R.string.reward_total_workouts_description), "reward_fg_workouts", thresholds = mapOf(RewardTier.WOOD to 1.0, RewardTier.BRONZE to 5.0, RewardTier.SILVER to 15.0, RewardTier.GOLD to 30.0, RewardTier.PLATINUM to 75.0)),
        RewardDefinition("workout_total_volume", RewardType.WORKOUT_TOTAL_VOLUME, RewardStringRefs(R.string.reward_workout_total_volume_title, R.string.reward_workout_total_volume_description), "reward_fg_total_weight", thresholds = mapOf(RewardTier.WOOD to 1000.0, RewardTier.BRONZE to 3000.0, RewardTier.SILVER to 7500.0, RewardTier.GOLD to 12000.0, RewardTier.PLATINUM to 20000.0)),
        RewardDefinition("workout_total_reps", RewardType.WORKOUT_TOTAL_REPS, RewardStringRefs(R.string.reward_workout_total_reps_title, R.string.reward_workout_total_reps_description), "reward_fg_reps", thresholds = mapOf(RewardTier.WOOD to 30.0, RewardTier.BRONZE to 60.0, RewardTier.SILVER to 100.0, RewardTier.GOLD to 150.0, RewardTier.PLATINUM to 250.0)),
        RewardDefinition("daily_steps", RewardType.DAILY_STEPS, RewardStringRefs(R.string.reward_daily_steps_title, R.string.reward_daily_steps_description), "reward_fg_steps", thresholds = mapOf(RewardTier.WOOD to 3000.0, RewardTier.BRONZE to 5000.0, RewardTier.SILVER to 8000.0, RewardTier.GOLD to 10000.0, RewardTier.PLATINUM to 15000.0)),
        RewardDefinition("workout_streak", RewardType.WORKOUT_STREAK, RewardStringRefs(R.string.reward_workout_streak_title, R.string.reward_workout_streak_description), "reward_fg_streak", thresholds = mapOf(RewardTier.WOOD to 2.0, RewardTier.BRONZE to 3.0, RewardTier.SILVER to 5.0, RewardTier.GOLD to 7.0, RewardTier.PLATINUM to 14.0)),
        RewardDefinition("weekly_consistency", RewardType.WEEKLY_CONSISTENCY, RewardStringRefs(R.string.reward_weekly_consistency_title, R.string.reward_weekly_consistency_description), "reward_fg_consistency", thresholds = mapOf(RewardTier.WOOD to 1.0, RewardTier.BRONZE to 2.0, RewardTier.SILVER to 3.0, RewardTier.GOLD to 4.0, RewardTier.PLATINUM to 5.0)),
        RewardDefinition("exercise_max_weight_bench_barbell_press", RewardType.EXERCISE_MAX_WEIGHT, RewardStringRefs(R.string.reward_strength_chest_title, R.string.reward_strength_chest_description), "reward_fg_exercise_record", "bench_barbell_press", mapOf(RewardTier.WOOD to 20.0, RewardTier.BRONZE to 40.0, RewardTier.SILVER to 60.0, RewardTier.GOLD to 80.0, RewardTier.PLATINUM to 100.0)),
        RewardDefinition("exercise_max_weight_barbell_squat", RewardType.EXERCISE_MAX_WEIGHT, RewardStringRefs(R.string.reward_strength_legs_title, R.string.reward_strength_legs_description), "reward_fg_exercise_record", "barbell_squat", mapOf(RewardTier.WOOD to 30.0, RewardTier.BRONZE to 60.0, RewardTier.SILVER to 90.0, RewardTier.GOLD to 120.0, RewardTier.PLATINUM to 150.0)),
        RewardDefinition("exercise_max_weight_machine_row", RewardType.EXERCISE_MAX_WEIGHT, RewardStringRefs(R.string.reward_strength_back_title, R.string.reward_strength_back_description), "reward_fg_exercise_record", "machine_row", mapOf(RewardTier.WOOD to 25.0, RewardTier.BRONZE to 45.0, RewardTier.SILVER to 65.0, RewardTier.GOLD to 85.0, RewardTier.PLATINUM to 110.0)),
        RewardDefinition("exercise_max_weight_machine_shoulder_press", RewardType.EXERCISE_MAX_WEIGHT, RewardStringRefs(R.string.reward_strength_shoulders_title, R.string.reward_strength_shoulders_description), "reward_fg_exercise_record", "machine_shoulder_press", mapOf(RewardTier.WOOD to 15.0, RewardTier.BRONZE to 30.0, RewardTier.SILVER to 45.0, RewardTier.GOLD to 60.0, RewardTier.PLATINUM to 80.0)),
        RewardDefinition("body_progress_entries", RewardType.BODY_PROGRESS_ENTRIES, RewardStringRefs(R.string.reward_body_progress_title, R.string.reward_body_progress_description), "reward_fg_body_progress", thresholds = mapOf(RewardTier.WOOD to 1.0, RewardTier.BRONZE to 3.0, RewardTier.SILVER to 7.0, RewardTier.GOLD to 15.0, RewardTier.PLATINUM to 30.0)),
        RewardDefinition("ai_exercise_created", RewardType.AI_EXERCISE_CREATED, RewardStringRefs(R.string.reward_ai_exercise_title, R.string.reward_ai_exercise_description), "reward_fg_ai_exercise", thresholds = mapOf(RewardTier.WOOD to 1.0, RewardTier.BRONZE to 3.0, RewardTier.SILVER to 5.0, RewardTier.GOLD to 10.0, RewardTier.PLATINUM to 20.0)),
        RewardDefinition("ai_template_created", RewardType.AI_TEMPLATE_CREATED, RewardStringRefs(R.string.reward_ai_template_title, R.string.reward_ai_template_description), "reward_fg_ai_template", thresholds = mapOf(RewardTier.WOOD to 1.0, RewardTier.BRONZE to 2.0, RewardTier.SILVER to 4.0, RewardTier.GOLD to 7.0, RewardTier.PLATINUM to 12.0)),
        RewardDefinition("health_connect_connected", RewardType.HEALTH_CONNECT_CONNECTED, RewardStringRefs(R.string.reward_health_connect_title, R.string.reward_health_connect_description), "reward_fg_health_connect", thresholds = mapOf(RewardTier.PLATINUM to 1.0)),
        RewardDefinition("equipment_recognizer_used", RewardType.EQUIPMENT_RECOGNIZER_USED, RewardStringRefs(R.string.reward_equipment_recognizer_title, R.string.reward_equipment_recognizer_description), "reward_fg_equipment_recognizer", thresholds = mapOf(RewardTier.PLATINUM to 1.0))
    )

    fun byId(id: String): RewardDefinition? = all.firstOrNull { it.id == id }
}
